import { pdf, Font } from '@react-pdf/renderer'
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'
import { createElement } from 'react'

// Register Noto Sans Khmer for Khmer script support (hosted locally)
Font.register({
  family: 'NotoSansKhmer',
  fonts: [
    { src: '/fonts/NotoSansKhmer-Regular.ttf', fontWeight: 400 },
    { src: '/fonts/NotoSansKhmer-Bold.ttf', fontWeight: 700 },
  ],
})

// Disable hyphenation (causes issues with Khmer)
Font.registerHyphenationCallback((word: string) => [word])

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'NotoSansKhmer',
    fontSize: 11,
    color: '#1a1a1a',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    paddingBottom: 16,
    borderBottom: '1 solid #e5e5e5',
  },
  logo: {
    width: 32,
    height: 32,
    marginRight: 10,
    borderRadius: 6,
  },
  headerText: {
    fontSize: 18,
    fontFamily: 'NotoSansKhmer',
    fontWeight: 'bold' as const,
    color: '#10a37f',
  },
  headerSub: {
    fontSize: 9,
    color: '#888',
    marginTop: 2,
  },
  sectionTitle: {
    fontSize: 13,
    fontFamily: 'NotoSansKhmer',
    fontWeight: 'bold' as const,
    color: '#1a1a1a',
    marginTop: 16,
    marginBottom: 8,
  },
  paragraph: {
    fontSize: 11,
    lineHeight: 1.6,
    marginBottom: 4,
    color: '#333',
  },
  bullet: {
    flexDirection: 'row',
    marginBottom: 4,
    paddingLeft: 8,
  },
  bulletDot: {
    width: 12,
    fontSize: 11,
    color: '#10a37f',
  },
  bulletText: {
    flex: 1,
    fontSize: 11,
    lineHeight: 1.5,
    color: '#333',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTop: '1 solid #e5e5e5',
    paddingTop: 8,
  },
  footerText: {
    fontSize: 8,
    color: '#aaa',
  },
  transcriptSection: {
    marginTop: 20,
    paddingTop: 16,
    borderTop: '1 solid #e5e5e5',
  },
  transcriptText: {
    fontSize: 9,
    lineHeight: 1.6,
    color: '#666',
  },
})

function parseSummaryToSections(markdown: string) {
  const sections: { title: string; items: string[] }[] = []
  let currentSection: { title: string; items: string[] } | null = null

  const lines = markdown.split('\n')
  for (const line of lines) {
    const trimmed = line.trim()
    if (trimmed.startsWith('### ') || trimmed.startsWith('## ')) {
      if (currentSection) sections.push(currentSection)
      currentSection = { title: trimmed.replace(/^#{2,3}\s+/, ''), items: [] }
    } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      const text = trimmed.replace(/^[-*]\s+(\[.\]\s+)?/, '')
      if (text && currentSection) currentSection.items.push(text)
    } else if (trimmed.startsWith('**') && trimmed.includes(':')) {
      // Bold label like **Duration:** 30 minutes
      const text = trimmed.replace(/\*\*/g, '')
      if (currentSection) currentSection.items.push(text)
    } else if (trimmed && currentSection) {
      currentSection.items.push(trimmed)
    }
  }
  if (currentSection) sections.push(currentSection)

  return sections
}

function MeetingPdfDocument({ summary, transcript, duration }: {
  summary: string
  transcript: string
  duration: number
}) {
  const sections = parseSummaryToSections(summary)
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })

  return createElement(Document, {},
    createElement(Page, { size: 'A4', style: styles.page },
      // Header
      createElement(View, { style: styles.header },
        createElement(View, {},
          createElement(Text, { style: styles.headerText }, 'AngkorAI Meeting Summary'),
          createElement(Text, { style: styles.headerSub },
            `${date}${duration > 0 ? ` · ${Math.round(duration / 60)} minutes` : ''}`
          ),
        ),
      ),
      // Sections
      ...sections.map((section, i) =>
        createElement(View, { key: i },
          createElement(Text, { style: styles.sectionTitle }, section.title),
          ...section.items.map((item, j) =>
            createElement(View, { key: j, style: styles.bullet },
              createElement(Text, { style: styles.bulletDot }, '•'),
              createElement(Text, { style: styles.bulletText }, item),
            )
          ),
        )
      ),
      // Transcript
      transcript && createElement(View, { style: styles.transcriptSection },
        createElement(Text, { style: styles.sectionTitle }, 'Full Transcript'),
        createElement(Text, { style: styles.transcriptText }, transcript.slice(0, 3000)),
        transcript.length > 3000 && createElement(Text, { style: styles.transcriptText }, '... [truncated]'),
      ),
      // Footer
      createElement(View, { style: styles.footer },
        createElement(Text, { style: styles.footerText }, 'Generated by AngkorAI · www.angkorai.ai'),
        createElement(Text, { style: styles.footerText }, date),
      ),
    )
  )
}

export async function generateMeetingPdf(summary: string, transcript: string, duration: number) {
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const doc = createElement(MeetingPdfDocument, { summary, transcript, duration }) as any
    const blob = await pdf(doc).toBlob()

    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `AngkorAI-Meeting-Summary-${new Date().toISOString().split('T')[0]}.pdf`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  } catch (err) {
    console.error('PDF generation failed:', err)
    alert('PDF export failed. Try copying the summary instead.')
  }
}
