/**
 * Generate a meeting PDF using the browser's native print functionality.
 * This correctly renders all languages including Khmer script.
 */
export async function generateMeetingPdf(summary: string, transcript: string, duration: number) {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })
  const durationText = duration > 0 ? ` - ${Math.round(duration / 60)} minutes` : ''

  // Convert markdown to simple HTML
  let html = summary
    .replace(/^## (.+)$/gm, '<h2 style="color:#10a37f;font-size:18px;margin:16px 0 8px">$1</h2>')
    .replace(/^### (.+)$/gm, '<h3 style="font-size:14px;margin:14px 0 6px;font-weight:bold">$1</h3>')
    .replace(/^\*\*(.+?)\*\*$/gm, '<p style="font-weight:bold;margin:4px 0">$1</p>')
    .replace(/^- \[ \] (.+)$/gm, '<p style="margin:3px 0 3px 16px">☐ $1</p>')
    .replace(/^- \[x\] (.+)$/gm, '<p style="margin:3px 0 3px 16px">☑ $1</p>')
    .replace(/^- (.+)$/gm, '<p style="margin:3px 0 3px 16px">• $1</p>')
    .replace(/^\* (.+)$/gm, '<p style="margin:3px 0 3px 16px">• $1</p>')
    .replace(/^  (.+)$/gm, '<p style="margin:1px 0 6px 20px;color:#444;font-size:11px">$1</p>')
    .replace(/\n\n/g, '<br/>')

  const printContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>AngkorAI Meeting Summary</title>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+Khmer:wght@400;700&display=swap');
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
          font-family: 'Noto Sans Khmer', 'Noto Sans', Arial, sans-serif;
          font-size: 12px;
          color: #1a1a1a;
          padding: 40px;
          max-width: 800px;
          margin: 0 auto;
        }
        .header {
          border-bottom: 2px solid #10a37f;
          padding-bottom: 12px;
          margin-bottom: 20px;
        }
        .header h1 {
          color: #10a37f;
          font-size: 22px;
          margin-bottom: 4px;
        }
        .header .date {
          color: #888;
          font-size: 11px;
        }
        .summary { line-height: 1.7; }
        .transcript {
          margin-top: 24px;
          padding-top: 16px;
          border-top: 1px solid #ddd;
        }
        .transcript h3 { margin-bottom: 8px; }
        .transcript p {
          font-size: 10px;
          color: #666;
          line-height: 1.6;
        }
        .footer {
          margin-top: 30px;
          padding-top: 10px;
          border-top: 1px solid #ddd;
          display: flex;
          justify-content: space-between;
          font-size: 9px;
          color: #aaa;
        }
        @media print {
          body { padding: 20px; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>AngkorAI Meeting Summary</h1>
        <div class="date">${date}${durationText}</div>
      </div>
      <div class="summary">${html}</div>
      ${transcript ? `
        <div class="transcript">
          <h3>Full Transcript</h3>
          <p>${transcript.replace(/\n/g, '<br/>')}</p>
        </div>
      ` : ''}
      <div class="footer">
        <span>Generated by AngkorAI - www.angkorai.ai</span>
        <span>${date}</span>
      </div>
    </body>
    </html>
  `

  // Open a new window and trigger print (Save as PDF)
  const printWindow = window.open('', '_blank')
  if (!printWindow) {
    alert('Please allow popups to export PDF.')
    return
  }

  printWindow.document.write(printContent)
  printWindow.document.close()

  // Wait for Khmer font to fully load, then print
  printWindow.onload = () => {
    if (printWindow.document.fonts) {
      printWindow.document.fonts.ready.then(() => {
        setTimeout(() => printWindow.print(), 300)
      })
    } else {
      setTimeout(() => printWindow.print(), 1500)
    }
  }
}
